### ISSUE TITLE
crash when talking to pilote

### ISSUE THREAD

**Issue by seppp** [FoxBytes/IncognitoBugs#1]
game just CTDs after random times when talking to pilot (first thing to talk to)

**Comment by Maxwolf** [comment]
That is very strange, all files are verified and ok? If it keeps happening stick -log for startup parameter and the game will generate log files with any fatal errors.

The logs would be in windows appdata roaming folder under Incognito/Logs. If you can get a crash this way I would be able to determine what exactly is happening. Never seen it crash before in multiple choice dialog.

**Comment by seppp** [comment]
found out it happenes only when NOT in fullscreen mode.

**Comment by Maxwolf** [comment]
Thank you for this info, will check here!

**Comment by seppp** [comment]
Log started: 4/16/2015 9:03:43 PM
Game 1.2
Fatal: RendererWorld: Render frame failed (OGRE EXCEPTION(3:RenderingAPIException): Error Presenting surfaces in D3D9RenderWindow::swapBuffers at ..\src\OgreD3D9RenderWindow.cpp (line 953)).
   bei System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   bei System.Environment.get_StackTrace()
   bei Engine.Log.A()
   bei Engine.Log.Fatal(String text)
   bei Engine.Renderer.RendererWorld.A(RenderTarget A, Boolean a)
   bei Engine.Renderer.RendererWorld._RenderOneFrame()
   bei Engine.EngineApp.E()
   bei Engine.EngineApp.A(Boolean A)
   bei a.aD.RunMessageLoop()
   bei Engine.EngineApp.Run()
   bei Game.Program.Main2()
   bei Game.Program.Main(String[] Args)

**Comment by Maxwolf** [comment]
That looks like the renderer is trying to call some function that your card doesn't support and it's crashing hard.

What GPU are you using? And do you have the latest drivers installed for it?

**Comment by seppp** [comment]
nvidiy GeForce 650M, running in a Dual-Monitor setup. incognito is set via nvidia software to use GPU not the internal intel graphics.

older errorlog, maybe related:


Log started: 3/28/2015 11:37:37 AM
Game 1.2
Fatal: RendererWorld: Initializing window failed (OGRE EXCEPTION(3:RenderingAPIException): Failed to create Direct3D9 Device: Invalid call in D3D9RenderWindow::createD3DResources at ..\src\OgreD3D9RenderWindow.cpp (line 722)).
   bei System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   bei System.Environment.get_StackTrace()
   bei Engine.Log.A()
   bei Engine.Log.Fatal(String text)
   bei Engine.Renderer.RendererWorld.A(String A, Boolean a, Boolean B, String b, _RenderTimerManager C, Boolean c)
   bei Engine.Renderer.RendererWorld._Init(String renderSystemAssemblyFileName, Boolean startedAtFullScreen, Boolean multiMonitorMode, String fontManagerDefaultLanguage, _RenderTimerManager renderTimerManager, Boolean isEditor)
   bei Engine.EngineApp.Create()
   bei Game.Program.Main2()
   bei Game.Program.Main(String[] Args)

**Comment by Maxwolf** [comment]
Try using the Configurator.exe in the games directory, it will let you tell the engine which graphics card you would like to use. This might be what you just said, two GPU's and engine is confused about which one to use.

Thankfully there is something in place, let me know how that goes.

**Comment by seppp** [comment]
it works well with the GL renderer. with direct3D ther is not even an option for the nvidia GPU in the configurator.

**Comment by Maxwolf** [comment]
After more investigation I am curious what would cause the GPU to not show up in Direct3D. Perhaps it is being used to drive your external monitor, or something is wrong with DirectX install. The configurator asks DirectX for a list of available drivers to get that list you can select from.

You were able to play the game without problems using OpenGL?

**Comment by seppp** [comment]
yes, no problems with Open GL.
and jfyi i can play other DirectX games without problems.

**Comment by Maxwolf** [comment]
Ok, since you can play using OpenGL I am going to close this. I would need to actually debug the game on your hardware to fix it, hopefully in the future I can get ahold of a laptop with multiple GPU's in it.
